apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: gitea-registry-sync
spec:
  hostAPI: https://infisical.noel.sh/api
  resyncInterval: 3600
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: "shared"
        envSlug: "prod"
        secretsPath: "/ci"
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: miniflux-ai
  managedSecretReference:
    secretName: gitea-registry
    secretNamespace: miniflux-ai
    secretType: kubernetes.io/dockerconfigjson
    creationPolicy: Owner
    template:
      includeAllSecrets: false
      data:
        .dockerconfigjson: '{"auths":{"git.noel.sh":{"username":"ci","password":"{{ .GITEA_REGISTRY_TOKEN.Value }}","auth":"{{ printf "ci:%s" .GITEA_REGISTRY_TOKEN.Value | b64enc }}"}}}'
